name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get/Clone code
      #uses is for using actions
        uses: actions/checkout@4.2.2            
      - name: Setup NodeJS
        uses: actions/setup-node@4.2.0
        with: 
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test



